### ISSUE TITLE
error for building 

### ISSUE THREAD

**Issue by CybCroww** [RisingTechOSS/android#9]
Failed to compile android/soong/cmd/soong_ui: "/mnt/risingOS/prebuilts/go/linux-x86/pkg/tool/linux_amd64/compile -N -l -o /mnt/risingOS/out/.soong_ui_intermediates/android-soong-bazel/android/soong/bazel.a -p android/soong/bazel -complete -pack -nolocalimports -c 20 -trimpath /mnt/risingOS -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-metrics -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-proptools -I /mnt/risingOS/out/.soong_ui_intermediates/google.golang.org-protobuf-proto -I /mnt/risingOS/out/.soong_ui_intermediates/prebuilts-bazel-common-proto-analysis_v2 /mnt/risingOS/build/soong/bazel/aquery.go /mnt/risingOS/build/soong/bazel/bazel_proxy.go /mnt/risingOS/build/soong/bazel/configurability.go /mnt/risingOS/build/soong/bazel/constants.go /mnt/risingOS/build/soong/bazel/properties.go /mnt/risingOS/build/soong/bazel/testing.go": exit status 2                                                                                   exit status 1                                                                                                                                           Device topaz not found. Attempting to retrieve device repositories from GitHub (http://github.com/RisingOSS-devices).                                   Repository for topaz not found in the RisingOSS-devices Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.                                                                                                                                   Failed to compile android/soong/cmd/soong_ui: "/mnt/risingOS/prebuilts/go/linux-x86/pkg/tool/linux_amd64/compile -N -l -o /mnt/risingOS/out/.soong_ui_intermediates/android-soong-bazel/android/soong/bazel.a -p android/soong/bazel -complete -pack -nolocalimports -c 20 -trimpath /mnt/risingOS -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-metrics -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-proptools -I /mnt/risingOS/out/.soong_ui_intermediates/google.golang.org-protobuf-proto -I /mnt/risingOS/out/.soong_ui_intermediates/prebuilts-bazel-common-proto-analysis_v2 /mnt/risingOS/build/soong/bazel/aquery.go /mnt/risingOS/build/soong/bazel/bazel_proxy.go /mnt/risingOS/build/soong/bazel/configurability.go /mnt/risingOS/build/soong/bazel/constants.go /mnt/risingOS/build/soong/bazel/properties.go /mnt/risingOS/build/soong/bazel/testing.go": exit status 2                                                                                   exit status 1                                                                                                                                           Failed to compile android/soong/cmd/soong_ui: "/mnt/risingOS/prebuilts/go/linux-x86/pkg/tool/linux_amd64/compile -N -l -o /mnt/risingOS/out/.soong_ui_intermediates/android-soong-bazel/android/soong/bazel.a -p android/soong/bazel -complete -pack -nolocalimports -c 20 -trimpath /mnt/risingOS -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-metrics -I /mnt/risingOS/out/.soong_ui_intermediates/github.com-google-blueprint-proptools -I /mnt/risingOS/out/.soong_ui_intermediates/google.golang.org-protobuf-proto -I /mnt/risingOS/out/.soong_ui_intermediates/prebuilts-bazel-common-proto-analysis_v2 /mnt/risingOS/build/soong/bazel/aquery.go /mnt/risingOS/build/soong/bazel/bazel_proxy.go /mnt/risingOS/build/soong/bazel/configurability.go /mnt/risingOS/build/soong/bazel/constants.go /mnt/risingOS/build/soong/bazel/properties.go /mnt/risingOS/build/soong/bazel/testing.go": exit status 2
exit status 1

** Don't have a product spec for: 'rising_topaz'
** Do you have the right repo manifest?

how to fix?

**Comment by Shivamingale3** [comment]
@CybCroww I'm facing this too did you find any fix?

**Comment by CybCroww** [comment]
> @CybCrowwЯ тоже с этим столкнулся, вы нашли какое-нибудь решение?
no

**Comment by yucellmustafa** [comment]
sources are still secret.
